Algoritmo "CalculaConsumo"
// Disciplina  : Lógica de Programação
// Professor   : Adriano Leite da Silva
// Descrição   : Calcula o consumo médio de um carro
// Data atual  : 14/06/2018
Var
distanciaPercorrida, combustivel: real

Inicio
Escreva("Digite a distância percorrida: ")
Leia(distanciaPercorrida)

Escreva("Digite o combustivel consumido: ")
Leia(combustivel)

Escreva("O carro teve consumo médio de: ", distanciaPercorrida/combustivel)
Fimalgoritmo
